--INSERT INTO PRODUCT (name, description, brand, price, category, releaseDate, productAvailable, stockQuantity)
--VALUES ('Smartphone', 'A high-end smartphone with excellent features', 'TechBrand', 699.99, 'Electronics', '2024-01-15', true, 50);

--INSERT INTO PRODUCT (name, description, brand, price, category, RELEASE_DATE, productAvailable, stockQuantity)
--VALUES ('Gaming Laptop', 'A powerful gaming laptop with a high-performance GPU', 'GameTech', 1499.99, 'Computers', '2023-11-25', true, 30);
--
--INSERT INTO PRODUCT (name, description, brand, price, category, RELEASE_DATE, productAvailable, stockQuantity)
--VALUES ('Wireless Headphones', 'Noise-cancelling over-ear headphones', 'SoundX', 199.99, 'Accessories', '2024-03-10', true, 100);
--
--INSERT INTO PRODUCT (name, description, brand, price, category, RELEASE_DATE, productAvailable, stockQuantity)
--VALUES ('Smartwatch', 'A sleek smartwatch with fitness tracking features', 'Wearables Co.', 249.50, 'Wearables', '2024-05-01', true, 75);
--
--INSERT INTO PRODUCT (name, description, brand, price, category, RELEASE_DATE, productAvailable, stockQuantity)
--VALUES ('4K Smart TV', 'A 55-inch smart TV with stunning 4K resolution', 'VisionPro', 799.99, 'Home Electronics', '2023-12-20', false, 0);
--
--INSERT INTO PRODUCT (name, description, brand, price, category, RELEASE_DATE, productAvailable, stockQuantity)
--VALUES ('Bluetooth Speaker', 'Portable speaker with excellent sound quality', 'MusicLife', 99.99, 'Audio', '2023-10-15', true, 150);
--
--INSERT INTO PRODUCT (name, description, brand, price, category, RELEASE_DATE, productAvailable, stockQuantity)
--VALUES ('Electric Kettle', '1.5-liter kettle with fast boiling technology', 'KitchenEssentials', 49.99, 'Kitchen Appliances', '2024-01-05', true, 200);

